"""``generate`` — the live generation-source façade (SOURCE → INDEX in one call).

The generate sibling of :func:`foley.sources.pull.add_from`: resolve a registered
:class:`~foley.sources.base.GenerateAdapter`, synthesize a sound from a prompt, and
run the resulting bytes through the SAME :func:`foley.index.ingest.ingest_one`
pipeline the local, bulk, and retrieve paths use — so decode / QC / embed / tag /
store are **not forked**. The division of labor mirrors ``add_from`` exactly: the
ADAPTER owns audio synthesis + license construction (it holds the model, seed, and
resolved native params), the FAÇADE owns the ``ingest_one`` call + the
:class:`~foley.index.ingest.IngestReport`.

Two differences from the retrieve path, both load-bearing:

* **By-value storage — the generation flywheel.** Both generator licenses
  (``Stability-Community``, ``ElevenLabs-SFX``) carry ``cache_bytes_ok=True``, so
  the bytes are stored by-value (the opposite of Freesound's by-reference); every
  generation becomes a first-class, re-searchable, locally-served library entry —
  a future free retrieval. The id is the decoded-PCM content hash
  (``sound_id=None``), so a byte-identical regeneration content-dedups
  (``skipped_dup``) and is never stored twice.
* **Operator-consented AI-training gate.** Both generator licenses carry
  ``ai_training_ok=False``, which ``ingest_one``'s universal fail-closed gate would
  reject. The user calling :func:`foley.generate` and keeping the result IS the
  explicit consent (they asked to create + persist THIS sound), so the façade calls
  ``ingest_one(..., allow_ai_training_forbidden=True)`` — the SAME lever
  :func:`foley.bootstrap.bootstrap` uses for Sonniss / BBC RemArc. The consent is to
  *embed + persist only*: ``ai_training_ok`` stays ``False`` on the record, so
  :func:`foley.keep` still refuses the sound for any ``IntendedUse(will_train=True)``
  downstream.

The public :func:`foley.generate` (a thin wrapper in :mod:`foley`) returns the
single stored :class:`~foley.base.Candidate` (report 10 §4.2); this workhorse
returns the full :class:`~foley.index.ingest.IngestReport` for ``add_from``-symmetric
resilience — a backend failure becomes a recorded ``error`` entry, never an
unhandled exception.
"""

from __future__ import annotations

from typing import Optional

from ..base import Candidate, CandidateOrigin
from ..index.ingest import IngestReport, IngestResult, ingest_one
from .registry import get_source

#: The consent note stamped on a stored generation whose license forbids AI
#: training (mirrors :func:`foley.bootstrap.bootstrap`'s Ring-2 acknowledgement).
_CONSENT_NOTE = "AI-training restriction acknowledged by operator (consent recorded)"


class GenerationError(RuntimeError):
    """Raised by :func:`foley.generate` when a backend yields no stored sound.

    Carries the full :class:`~foley.index.ingest.IngestReport` and the terminal
    :attr:`status` so a caller can react distinctly to ``quarantined`` (QC-rejected —
    e.g. regenerate), ``rights_blocked``, or ``error``. The lower-level
    :func:`generate` workhorse never raises this — it always returns an inspectable
    report; only the public :func:`foley.generate` promise raises.

    Attributes:
        report: The :class:`~foley.index.ingest.IngestReport` from the run.
        status: The terminal :class:`~foley.index.ingest.IngestResult` status
            (``'quarantined'`` | ``'rights_blocked'`` | ``'error'`` | …).
    """

    def __init__(self, message: str, *, report: IngestReport, status: Optional[str]):
        super().__init__(message)
        self.report = report
        self.status = status


def candidate_of(result: IngestResult) -> Candidate:
    """Wrap a stored :class:`~foley.index.ingest.IngestResult` as a generated candidate.

    The report-10 §4.2 shape: retrieval and generation return the same
    :class:`~foley.base.Candidate`, differing only in ``origin``. Use on a
    ``pass`` / ``warn`` result (its ``record`` is the canonical, stored
    :class:`~foley.base.SoundRecord`).

    Args:
        result: A stored ingest result (``result.record`` is not ``None``).

    Returns:
        A :class:`~foley.base.Candidate` with ``origin=CandidateOrigin.generated``.
    """
    return Candidate(sound=result.record, origin=CandidateOrigin.generated)


def generate(
    prompt: str,
    *,
    backend: str = "stable_audio",
    library=None,
    store: bool = True,
    adapter=None,
    **affordances,
) -> IngestReport:
    """Generate a sound via ``backend`` and ingest it (by-value) into ``library``.

    Progressive disclosure: ``generate("a single wooden door creak")`` works out of
    the box (the local Stable Audio Open backend, into the process-wide default
    library); every other knob is an optional keyword. The generated bytes are
    routed through the shared :func:`~foley.index.ingest.ingest_one` pipeline
    (decode → QC → embed → tag → store), stored by-value with a content-hash id.

    Args:
        prompt: The natural-language sound description.
        backend: A registered generate-source name (``'stable_audio'`` (default,
            local) | ``'elevenlabs'`` (hosted)).
        library: Target :class:`~foley.index.library.SoundLibrary` (default: the
            process-wide default library).
        store: If ``False``, synthesize + enrich but do not add to the library
            (probe/QC/embed only — a preview).
        adapter: An optional pre-built adapter to use instead of the registry's
            (the dependency-injection seam — a test passes a fake-transport /
            fake-pipeline adapter; production omits it and the registry lazily
            builds one).
        **affordances: Unified generation affordances forwarded to the adapter's
            ``generate`` (``duration``, ``prompt_influence``, ``negative_prompt``,
            ``steps``, ``seed``, ``loop``, ``output_format`` — see
            :data:`foley.base.GENERATION_AFFORDANCES`); unsupported ones are
            warn-and-dropped per the source's ``on_unsupported_param``.

    Returns:
        An :class:`~foley.index.ingest.IngestReport` — inspect ``.ingested`` for the
        stored record (``storage_mode == by_value``) and ``.summary()`` for counts.
        A backend or ingest failure is recorded as a single ``error`` result, never
        raised (``add_from``-symmetric resilience).
    """
    from ..index.library import default_library

    lib = library if library is not None else default_library()
    gen = adapter if adapter is not None else get_source(backend)["adapter"]

    report = IngestReport(root=f"{backend}:{prompt}")
    # A synthesis failure (auth / rate-limit / model load / bad response) yields an
    # inspectable report with one error entry, never an unhandled exception.
    try:
        clip = gen.generate(prompt, **affordances)
    except Exception as exc:
        report.record(
            IngestResult(id=f"{backend}:generate", status="error", error=repr(exc))
        )
        return report

    lic = clip.candidate.sound.license
    # The bytes ride WITH the candidate on the transient GeneratedClip (adapters
    # never touch storage); the façade hands them to the ONE shared ingest_one —
    # by-value (cache_bytes_ok=True), PCM-hash id (sound_id=None), with operator
    # consent for the ai_training_ok=False generator license. A separate try guards
    # the fetch/decode so an undecodable response is an error, not a crash.
    try:
        res = ingest_one(
            clip.audio_bytes,
            library=lib,
            sound_id=None,  # generated audio → decoded-PCM content-hash id (+dedup)
            license=lic,  # is_ai_generated + provenance + flags derived from license_id
            captioner=_metadata_captioner(prompt),
            seed_tags=(clip.candidate.sound.tags or None),
            store=store,
            allow_ai_training_forbidden=True,  # operator consent (embed+persist only)
        )
    except Exception as exc:
        report.record(
            IngestResult(id=f"{backend}:ingest", status="error", error=repr(exc))
        )
        return report

    # Surface the adapter's generation-time notes (unsupported-affordance drops,
    # output-format fallbacks) in the run report.
    if clip.notes:
        res.notes.extend(clip.notes)
    # Record the operator-consent acknowledgement on a stored generation whose
    # license forbids AI training (mirrors bootstrap's Ring-2 note). ai_training_ok
    # stays False on the record — keep() still rejects it for will_train uses.
    if res.status in ("pass", "warn") and not lic.ai_training_ok:
        res.notes.append(_CONSENT_NOTE)
    report.record(res)
    return report


def _metadata_captioner(prompt: str):
    """The prompt as the sound's caption (feeds the BM25 keyword index).

    Imported from :mod:`foley.bootstrap` locally to avoid a
    ``sources`` ↔ ``bootstrap`` import cycle (same seam :func:`add_from` uses).
    """
    from ..bootstrap import MetadataCaptioner

    return MetadataCaptioner(prompt) if prompt else None
